apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: example-quayecosystem
spec:
  quay:
    imagePullSecretName: redhat-pull-secret
    database:
      volumeSize: 100Gi
    registryBackends:
      - name: rhocs
        rhocs:
          hostname: s3.openshift-storage.svc
          secure: true
          port: 443
          accessKey: <YOUR-BUCKET-ACCESS-KEY>
          secretKey: <YOUR-BUCKET-SECRET-KEY>
          bucketName: quay-registry-bucket-d372bed5-2297-415d-b08e-88975e2b0a8b
    keepConfigDeployment: true
    deploymentStrategy: RollingUpdate
  clair:
    enabled: true
    imagePullSecretName: redhat-pull-secret
    updateInterval: "60m"
    configFiles:
      - secretName: quay-myorg-ca
        type: extraCaCert
    envVars:
    - name: HTTP_PROXY
      value: http://proxy.example.com:8080
    - name: HTTPS_PROXY
      value: http://proxy.example.com:8080
    - name: NO_PROXY
      value: .example.com,.cluster.local,.svc,10.0.0.0/16,10.128.0.0/14,127.0.0.1,127.0.0.1/8,172.30.0.0/16,localhost
