apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: example-quayecosystem
spec:
  quay:
    imagePullSecretName: redhat-quay-pull-secret
    database:
      volumeSize: 100Gi
    registryBackends:
      - name: rhocs
        rhocs:
          hostname: s3.openshift-storage.svc
          secure: true
          port: 443
          accessKey: <YOUR-BUCKET-ACCESS-KEY>
          secretKey: <YOUR-BUCKET-SECRET-KEY>
          bucketName: quay-registry-bucket-d372bed5-2297-415d-b08e-88975e2b0a8b
    keepConfigDeployment: true
    deploymentStrategy: RollingUpdate
  clair:
    enabled: true
    imagePullSecretName: redhat-quay-pull-secret
    updateInterval: "60m"
